glib: Silence a new clippy warning that requires Rust 1.65
error: casting the result of `from_raw_parts` to *const [u8]
   --> glib/src/variant_type.rs:140:16
    |
140 |             &*(slice::from_raw_parts(self.ptr.as_ptr() as *const u8, self.len) as *const [u8]
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `core::ptr::slice_from_raw_parts(self.ptr.as_ptr() as *const u8, self.len)`
    |
    = note: `-D clippy::cast-slice-from-raw-parts` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_slice_from_raw_parts

error: casting the result of `from_raw_parts` to *const [u8]
   --> glib/src/variant_type.rs:456:12
    |
456 |         &*(slice::from_raw_parts(ptr as *const u8, len) as *const [u8] as *const VariantTy)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `core::ptr::slice_from_raw_parts(ptr as *const u8, len)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_slice_from_raw_parts